compilers:
- compiler:
    spec: intel@=2021.10.0
    paths:
      cc: /opt/intel/oneapi/2023.2/compiler/2023.2.0/linux/bin/intel64/icc
      cxx: /opt/intel/oneapi/2023.2/compiler/2023.2.0/linux/bin/intel64/icpc
      f77: /opt/intel/oneapi/2023.2/compiler/2023.2.0/linux/bin/intel64/ifort
      fc: /opt/intel/oneapi/2023.2/compiler/2023.2.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules:
    - intel/2023.2
    environment:
      prepend_path:
        PATH: /opt/gcc/10.2.0/bin
        LD_LIBRARY_PATH: /opt/intel/oneapi/2023.2/compiler/2023.2.0/linux/compiler/lib/intel64_lin:/opt/gcc/10.2.0/lib64:/opt/gcc/10.2.0/lib
        CPATH: /opt/gcc/10.2.0/include
    extra_rpaths: []
- compiler:
    spec: oneapi@2024.2.1
    paths:
      cc: /opt/intel/oneapi/2024/compiler/2024.2/bin/icx
      cxx: /opt/intel/oneapi/2024/compiler/2024.2/bin/icpx
      f77: /opt/intel/oneapi/2024/compiler/2024.2/bin/ifort
      fc: /opt/intel/oneapi/2024/compiler/2024.2/bin/ifort
    flags:
      fflags: -diag-disable=10448
    operating_system: rocky8
    target: x86_64
    modules:
    - intel/2024.2
    environment:
      prepend_path:
        PATH: /opt/gcc/10.2.0/bin
        LD_LIBRARY_PATH: /opt/gcc/10.2.0/lib64:/opt/gcc/10.2.0/lib
        CPATH: /opt/gcc/10.2.0/include
      append_path:
        PATH: /opt/intel/oneapi/2024/compiler/2024.2/opt/compiler/include/intel64
    extra_rpaths: []
- compiler:
    spec: gcc@=13.3.0
    paths:
      cc: /opt/gcc/13.3/bin/gcc
      cxx: /opt/gcc/13.3/bin/g++
      f77: /opt/gcc/13.3/bin/gfortran
      fc: /opt/gcc/13.3/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules:
    - gcc/13.3
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=10.2.0
    paths:
      cc: /opt/gcc/10.2.0/bin/gcc
      cxx: /opt/gcc/10.2.0/bin/g++
      f77: /opt/gcc/10.2.0/bin/gfortran
      fc: /opt/gcc/10.2.0/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules:
    - gcc/10.2
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=8.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

