mirrors:
  local-source:
    fetch:
      url: file:///scratch4/NCEPDEV/stmp/role.epic/spack-stack/mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///scratch4/NCEPDEV/stmp/role.epic/spack-stack/mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
