packages:
  all:
    compiler:: [oneapi@2024.2.1]
    providers:
      mpi:: [intel-oneapi-mpi@2021.13]
      # Remove the next three lines to switch to intel-oneapi-mkl
      blas:: [openblas]
      fftw-api:: [fftw]
      lapack:: [openblas]
  mpi:
    buildable: False
  intel-oneapi-mpi:
    buildable: False
    externals:
    - spec: intel-oneapi-mpi@2021.13%oneapi@2024.2.1
      modules:
      - intel/2024.2.1
      - impi/2024.2.1
      prefix: /apps/oneapi
  intel-oneapi-mkl:
    # Remove buildable: False and uncomment externals section below to use intel-oneapi-mkl
    buildable: False
    #externals:
    #- spec: intel-oneapi-mkl@2022.0.2%intel@2021.5.0
    #  prefix: /apps/oneapi
  # DH* Remove this section to switch to intel-oneapi-mkl
  ectrans:
    require::
    - '@1.2.0 ~mkl +fftw'
  gsibec:
    require::
    - '@1.2.1 ~mkl'
  py-numpy:
    require::
    - '@1.26'
    - '^openblas'
  # *DH
  zlib-ng:
    require:
      - '~shared'
  cdo:
    require:
      - '@2.3.0'
