compilers:
- compiler:
    spec: intel@=2024.2.1
    paths:
      cc: /opt/intel/oneapi/compiler/2024.2.1/linux/bin/intel64/icpx
      cxx: /opt/intel/oneapi/compiler/2024.2.1/linux/bin/intel64/icpx
      f77: /opt/intel/oneapi/compiler/2024.2.1/linux/bin/intel64/ifort
      fc: /opt/intel/oneapi/compiler/2024.2.1/linux/bin/intel64/ifort
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules: []
    environment:
      prepend_path:
        PATH: /opt/rh/gcc-toolset-11/root/user/bin
        LD_LIBRARY_PATH: '/opt/intel/oneapi/compiler/2024.2.1/linux/compiler/lib/intel64_lin:/usr/lib64:/usr/lib'
        CPATH: /opt/rh/gcc-toolset-11/root/user/include
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.1
    paths:
      cc: /opt/rh/gcc-toolset-11/root/user/bin/gcc
      cxx: /opt/rh/gcc-toolset-11/root/user/bin/g++
      f77: /opt/rh/gcc-toolset-11/root/user/bin/gfortran
      fc: /opt/rh/gcc-toolset-11/root/user/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

