packages:
  all:
    compiler:: [oneapi@2024.2.1,gcc@11.2.1]
    providers:
      mpi:: [intel-oneapi-mpi@2023.13]
      # Remove the next three lines to switch to intel-oneapi-mkl
      blas:: [openblas]
      fftw-api:: [fftw]
      lapack:: [openblas]
  intel-oneapi-mpi:
    buildable: false
    externals:
    - spec: intel-oneapi-mpi@2021.13
      prefix: /opt/intel/oneapi
  intel-oneapi-mkl:
    buildable: False
  ectrans:
    require::
    - '@1.5.0 ~mkl +fftw'
  gsibec:
    require::
    - '@1.2.1 ~mkl'
  py-numpy:
    require::
    - '@:1.26.4 ^openblas'
  gmake:
    buildable: False