packages:
  all:
    compiler:: [intel@2021.10.0,gcc@11.2.1]
    providers:
      mpi:: [intel-oneapi-mpi@2021.10.0]
      # Remove the next three lines to switch to intel-oneapi-mkl
      blas:: [openblas]
      fftw-api:: [fftw]
      lapack:: [openblas]
  mpi:
    buildable: False
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.10.0%intel@2021.10.0
      prefix: /opt/intel/oneapi
  intel-oneapi-mkl:
    # Remove buildable: False and configure version+uncomment externals section below to use intel-oneapi-mkl
    buildable: False
    #externals:
    #- spec: intel-oneapi-mkl@2022.0.2%intel@2021.10.0
    #  prefix: /opt/intel/oneapi
  ectrans:
    require::
    - '@1.2.0 ~mkl +fftw'
  gsibec:
    require::
    - '@1.2.1 ~mkl'
  py-numpy:
    require::
    - '@:1.23 ^openblas'
