compilers:
- compiler:
    spec: oneapi@=2024.2.1
    paths:
      cc: /apps/spack-managed-x86_64_v3-v1.0/gcc-11.3.1/intel-oneapi-compilers-2024.2.1-podbez65l57ms4uba527kg7pomxk5y3m/compiler/2024.2/bin/icx
      cxx: /apps/spack-managed-x86_64_v3-v1.0/gcc-11.3.1/intel-oneapi-compilers-2024.2.1-podbez65l57ms4uba527kg7pomxk5y3m/compiler/2024.2/bin/icpx
      f77: /apps/spack-managed-x86_64_v3-v1.0/gcc-11.3.1/intel-oneapi-compilers-2024.2.1-podbez65l57ms4uba527kg7pomxk5y3m/compiler/2024.2/bin/ifort
      fc: /apps/spack-managed-x86_64_v3-v1.0/gcc-11.3.1/intel-oneapi-compilers-2024.2.1-podbez65l57ms4uba527kg7pomxk5y3m/compiler/2024.2/bin/ifort
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules:
    - spack-managed-x86-64_v3
    - intel-oneapi-compilers/2024.2.1
    environment:
      set:
        # https://github.com/ufs-community/ufs-weather-model/issues/2015#issuecomment-1864438186
        I_MPI_EXTRA_FILESYSTEM: 'ON'
        # Override system module settings for FC and F77 (they're set to ifx)
        F77: '/apps/spack-managed-x86_64_v3-v1.0/gcc-11.3.1/intel-oneapi-compilers-2024.2.1-podbez65l57ms4uba527kg7pomxk5y3m/compiler/2024.2/bin/ifort'
        FC: '/apps/spack-managed-x86_64_v3-v1.0/gcc-11.3.1/intel-oneapi-compilers-2024.2.1-podbez65l57ms4uba527kg7pomxk5y3m/compiler/2024.2/bin/ifort'
      prepend_path:
        PATH: /usr/bin
        LD_LIBRARY_PATH: /usr/lib:/usr/lib64
        CPATH: '/usr/include/c++/11:/usr/include/c++/11/x86_64-redhat-linux'
    extra_rpaths: []
- compiler:
    spec: intel@2021.9.0
    paths:
      cc: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/intel64/icc
      cxx: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/intel64/icpc
      f77: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/intel64/ifort
      fc: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules:
    - intel-oneapi-compilers/2023.1.0
    environment:
      set:
        # https://github.com/ufs-community/ufs-weather-model/issues/2015#issuecomment-1864438186
        I_MPI_EXTRA_FILESYSTEM: 'ON'
    extra_rpaths: []
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/gcc
      cxx: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/g++
      f77: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/gfortran
      fc: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/gfortran
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules:
    - gcc/12.2.0
    environment: {}
    extra_rpaths: []
