packages:
  # For addressing https://github.com/JCSDA/spack-stack/issues/1355
  #   Use system zlib instead of spack-built zlib-ng
  all:
    providers:
      zlib-api:: [zlib]
  zlib-api:
    buildable: False
  zlib:
    buildable: False
    externals:
    - spec: zlib@1.2.11
      prefix: /usr

  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.2
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.35.2
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.21
      prefix: /usr
  git:
    externals:
    - spec: git@2.31.1~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.1.2
      prefix: /apps/spack-managed/gcc-11.3.1/git-lfs-3.1.2-sjfqfgha27na65g3lrcqamncnryjoa7l
      modules:
      - git-lfs/3.1.2
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  grep:
    externals:
    - spec: grep@3.6
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  # Don't use, incomplete installation!
  #libtool:
  #  externals:
  #  - spec: libtool@2.4.6
  #    prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /usr
  # Don't use, issues with py-cryptography
  #openssl:
  #  externals:
  #  - spec: openssl@3.0.1
  #    prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.7.3
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
  subversion:
    externals:
    - spec: subversion@1.14.1
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.7
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.21.1
      prefix: /usr
  which:
    externals:
      - spec: which@2.21
        prefix: /usr
