compilers:
- compiler:
    spec: intel@2021.6.0
    paths:
      cc: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icc
      cxx: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icpc
      f77: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/ifort
      fc: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules:
    - intel-oneapi
    - compiler/2022.1.0
    environment:
      prepend_path:
        PATH: /cm/local/apps/gcc/11.2.0/bin
        CPATH: /cm/local/apps/gcc/11.2.0/include
        LD_LIBRARY_PATH: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin:/cm/local/apps/gcc/11.2.0/lib64:/cm/local/apps/gcc/11.2.0/lib
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: /cm/local/apps/gcc/11.2.0/bin/gcc
      cxx: /cm/local/apps/gcc/11.2.0/bin/g++
      f77: /cm/local/apps/gcc/11.2.0/bin/gfortran
      fc: /cm/local/apps/gcc/11.2.0/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules:
    - gcc/11.2.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2024.2.1
    paths:
      cc: /cm/shared/apps/intel/oneapi-2024.2.1/compiler/2024.2/bin/icx
      cxx: /cm/shared/apps/intel/oneapi-2024.2.1/compiler/2024.2/bin/icpx
      f77: /cm/shared/apps/intel/oneapi-2024.2.1/compiler/2024.2/bin/ifort
      fc: /cm/shared/apps/intel/oneapi-2024.2.1/compiler/2024.2/bin/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules:
    - intel-oneapi-2024.2.1
    - tbb/2021.13
    - compiler-rt/2024.2.1
    - compiler/2024.2.1
    environment:
      prepend_path:
        PATH: /cm/local/apps/gcc/11.2.0/bin
        CPATH: /cm/local/apps/gcc/11.2.0/include
        LD_LIBRARY_PATH: /cm/local/apps/gcc/11.2.0/lib64:/cm/local/apps/gcc/11.2.0/lib
    extra_rpaths: []
#- compiler:
#    spec: oneapi@2025.0.3
#    paths:
#      cc: /gpfs/neptune/spack-stack/oneapi-2025.0.3/compiler/2025.0/bin/icx
#      cxx: /gpfs/neptune/spack-stack/oneapi-2025.0.3/compiler/2025.0/bin/icpx
#      f77: /gpfs/neptune/spack-stack/oneapi-2025.0.3/compiler/2025.0/bin/ifx
#      fc: /gpfs/neptune/spack-stack/oneapi-2025.0.3/compiler/2025.0/bin/ifx
#    flags: {}
#    operating_system: rhel8
#    target: x86_64
#    modules:
#    - umf/0.9.1
#    - compiler-rt/2025.0.1
#    - tbb/2022.0
#    - compiler-intel-llvm/2025.0.1
#    environment:
#      prepend_path:
#        PATH: /cm/local/apps/gcc/11.2.0/bin
#        CPATH: /cm/local/apps/gcc/11.2.0/include
#        LD_LIBRARY_PATH: /cm/local/apps/gcc/11.2.0/lib64:/cm/local/apps/gcc/11.2.0/lib
#    extra_rpaths: []
