packages:
  all:
    compiler:: [gcc@11.2.0]
    providers:
      mpi:: [openmpi@4.1.5]
  mpi:
    buildable: False
  openmpi:
    buildable: False
    externals:
    - spec: openmpi@4.1.5%gcc@=11.2.0~cuda~cxx~cxx_exceptions~java~memchecker+pmi~static~wrapper-rpath fabrics=ucx schedulers=slurm
      # Note: slurm must be loaded before openmpi on Atlantis
      modules:
      - slurm
      - openmpi/mlnx/gcc/64/4.1.5a1
