packages:
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.30.117
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.30
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.61.1
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.1+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  git:
    externals:
    - spec: git@2.39.2+tcltk
      prefix: /software8/depot/git-2.39.2
  git-lfs:
    externals:
    - spec: git-lfs@3.3.0
      prefix: /software8/depot/git-2.39.2
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  grep:
    externals:
    - spec: grep@3.1
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.0p1
      prefix: /usr
  # Can no longer use, issues with py-cryptography
  #openssl:
  #  externals:
  #  - spec: openssl@1.1.1k
  #    prefix: /usr
  # Can't use with py-xnrl
  #perl:
  #  externals:
  #  - spec: perl@5.26.3~cpanm+shared+threads
  #    prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.4.2
      prefix: /usr
  subversion:
    externals:
    - spec: subversion@1.10.2
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.19.5
      prefix: /usr
