compilers:
- compiler:
    spec: gcc@11.2.1
    paths:
      cc: /opt/rh/gcc-toolset-11/root/user/bin/gcc
      cxx: /opt/rh/gcc-toolset-11/root/user/bin/g++
      f77: /opt/rh/gcc-toolset-11/root/user/bin/gfortran
      fc: /opt/rh/gcc-toolset-11/root/user/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

