packages:
  all:
    compiler:: [oneapi@2024.2.0,gcc@11.4.0]
    providers:
      mpi:: [intel-oneapi-mpi@2021.13]
  mpi:
    buildable: False
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.13%oneapi@2024.2.0
      prefix: /usr/local/intel/oneapi/2024
      modules:
      - mpi/impi/2021.13
  intel-oneapi-mkl:
    externals:
    - spec: intel-oneapi-mkl@2024.2.0
      prefix: /usr/local/intel/oneapi/2024
  intel-oneapi-runtime:
    externals:
    - spec: intel-oneapi-runtime@2024.2.0%oneapi@2024.2.0
      prefix: /usr/local/intel/oneapi/2024
