packages:
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.2
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.35.2~gold+headers
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.7.4
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.26.5
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.21
      prefix: /usr
  git:
    externals:
    - spec: git@2.43.5~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.4.1
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.7p1
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.32.1~cpanm~opcode+open+shared+threads
      prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.7.3
      prefix: /usr
  qt:
    buildable: False
    externals:
    - spec: qt@5.15.9
      prefix: /usr/lib64/qt5
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  texlive:
    externals:
    - spec: texlive@20200406
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.21.1
      prefix: /usr
  zlib:
    externals:
    - spec: zlib@1.2.11
      prefix: /usr
