spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: $env/install
    deprecated: true

  view: false

  include: []

  specs:
  - awscli
  - bacio
  - boost %intel
  - bufr
  - cdo
  - cfitsio
  - cmake
  - crtm
  - curl
  - ecflow ^boost%gcc
  - eckit
  - ecmwf-atlas
  - eigen
  - esmf
  - fckit
  - fms
  - g2
  - g2c
  - g2tmpl
  - gdal@3.8.5
  - geos
  - gfsio
  - gftl-shared
  - git
  - grib-util
  - gsl
  - gsl-lite
  - hdf5
  - imagemagick
  - ip
  - ip2
  - jasper
  - landsfcutil
  - libgeotiff
  - libiconv
  - libjpeg-turbo
  - libpng
  - libtiff
  - libxml2
  - libxrender
  - madis
  - mapl
  - mbedtls
  - met
  - metis
  - metplus
  - nccmp
  - gsi-ncdiag
  - nco
  - ncview
  - nemsio
  - nemsiogfs
  - netcdf-c
  - netcdf-fortran
  - perl
  - pigz
  - parallelio
  - pixman
  - proj
  - python
  - qhull
  - readline
  - rsync
  - scotch
  - sfcio
  - sigio
  - sp
  - subversion
  - udunits
  - upp
  - w3emc
  - w3nco
  - wgrib2
  - wrf-io
