packages:
  all:
    compiler:: [intel@2021.10.0,gcc@11.2.0]
    providers:
      mpi:: [cray-mpich@8.1.25]
  mpi:
    buildable: False
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.25%intel@2021.10.0 +wrappers
      modules:
      - craype/2.7.20
      - cray-mpich/8.1.25
      - libfabric/1.15.2.0
      - cray-pals/1.2.11
  intel-oneapi-mkl:
    # No intel-oneapi-mkl installed on Derecho, install via spack.
    # Prefer the version that Intel releases with the above compiler
    prefer:
    - '@2023.2.0'
  # Newer versions of patchelf (tested 0.18.0) don't build with Intel on Derecho
  patchelf:
    version:: ['0.17.2']
