packages:
  all:
    # To support hecflow01
    # target: [AMD EPYC]
     providers:
      zlib-api:: [zlib]
  zlib-api:
    buildable: False
  zlib:
    buildable: False
    externals:
    - spec: zlib@1.2.11
      prefix: /usr

# All other packages listed alphabetically
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.2
      prefix: /usr
  bash:
    externals:
    - spec: bash@5.1.8
      prefix: /usr
  berkeley-db:
    externals:
    - spec: berkeley-db@18.1.40
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/berkeley-db-18.1.40-tetbmt6446oglhqm4dnhpybup6ltpnno
  binutils:
    externals:
    - spec: binutils@2.35.2
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.13.90
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7-12
      prefix: /usr
  doxygen:
    externals:
    - spec: doxygen@1.11.0+graphviz~mscgen
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/doxygen-1.11.0-dbhxblaakcrhvmlrbgixvapnagjb2vkx
  file:
    externals:
    - spec: file@5.39
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0-6
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@10.03.1
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/ghostscript-10.03.1-womgp7wo5ax6gm3afwvf5szxy3w4ap4v
  git:
    externals:
    - spec: git@2.43.5+tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.5.1
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/git-lfs-3.5.1-7jkcmztw3ftdo66qelwz6vklovodmybk
      modules:
      - git-lfs/3.5.1
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  hwloc:
    externals:
    - spec: hwloc@2.4.1-5
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.21.1-1
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /usr
  mysql:
     buildable: False
     externals:
     - spec: mysql@8.0.35
       prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/mysql-8.0.35-727bhsgyo7yjbkc5sstcxmovbxacm4c5
       modules:
       - mysql/8.0.35
  openjdk:
    externals:
    - spec: openjdk@1.8.0.412.b08-2
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@1.7.3
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.2.3
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@3.2.3
      prefix: /apps/ruby/3.2.3
      modules:
      - ruby/3.2.3
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@7.1
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/texinfo-7.1-vtmy2xy3v7zn2ct4brekmagtpfbs5fmi
  texlive:
    externals:
    - spec: texlive@20220321
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/texlive-20220321-nwvwftavgdpph7ifqemmapdnrji33a7c
  wget:
    externals:
    - spec: wget@1.21.1
      prefix: /usr
  which:
    externals:
    - spec: which@2.21
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.5
      prefix: /usr
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
