packages:
  all:
    compiler:: [gcc@11.4.1]
    providers:
      mpi:: [openmpi@4.1.6]
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.1.6~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-libevent~internal-pmix~java+legacylaunchers~lustre~memchecker~openshmem~orterunprefix+pmi+romio+rsh~singularity+static+vt+wrapper-rpath fabrics=ucx schedulers=slurm
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/openmpi-4.1.6-auzmzlihoo7n6g254nqkguxtzrdzkyqv
      modules:
      - openmpi/4.1.6

  ectrans:
    require::
    - '~mkl +fftw'
  gsibec:
    require::
    - '~mkl'
  py-numpy:
    require::
    - '@1.26'
    - '^openblas'
  zlib-ng:
    require:
    - '~shared'
