compilers:
- compiler:
    spec: oneapi@=2024.2.1
    paths:
      cc: /opt/intel/oneapi/compiler/2024.2/bin/icx
      cxx: /opt/intel/oneapi/compiler/2024.2/bin/icpx
      f77: /opt/intel/oneapi/compiler/2024.2/bin/ifort
      fc: /opt/intel/oneapi/compiler/2024.2/bin/ifort
    flags: {}
    operating_system: ubuntu24.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu24.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

