packages:
  mysql:
    externals:
    - spec: mysql@8.0.41
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.21.4
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.38
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.10
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.9.0
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.21
      prefix: /usr
  git:
    externals:
    - spec: git@2.43.0~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.4.1
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.7
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.38.2~cpanm+opcode+open+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
  qt:
    buildable: false
    externals:
    - spec: qt@5.15.3
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.9
      prefix: /usr
  lcms:
    externals:
    - spec: lcms@2.13.1
      prefix: /usr
